version: '3.9'

services:
  backend:
    build: ./backend
    container_name: medicabinet-backend
    volumes:
      - ./:/app # mount the entire repository
    working_dir: /app
    ports:
      - "8085:8000"
    # Use reload for development; note the command is overridden here 
    # Use the full package path so that relative imports work
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: medicabinet-frontend
    volumes:
      - ./frontend:/app
      # Persist node_modules inside the container to avoid conflicts with host
      - /app/node_modules
    ports:
      - "5173:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    # Start the development server
    command: npm run dev

  db:
    image: postgres:15
    container_name: medicabinet-db
    restart: always
    environment:
      POSTGRES_USER: medicabinet
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: medicabinet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
