version: '3.9'

services:
  backend:
    image: dogiakos/medicine-cabinet-backend:latest
    container_name: medicabinet-backend
    ports:
      - "8085:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-medicabinet}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-medicabinet_db}
      POSTGRES_HOST: db
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
    depends_on:
      - db

  frontend:
    image: dogiakos/medicine-cabinet-frontend:latest
    container_name: medicabinet-frontend
    ports:
      - "5173:5173"

  db:
    image: postgres:15
    container_name: medicabinet-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-medicabinet}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-medicabinet_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
