version: '3.9'

services:
  backend:
    build: ./backend
    container_name: medicabinet-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: medicabinet-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    command: npm run dev

  db:
    image: postgres:15
    container_name: medicabinet-db
    restart: always
    environment:
      POSTGRES_USER: medicabinet
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: medicabinet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: