version: '3.9'

services:
  backend:
    build: ./backend
    container_name: medicabinet-backend
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: medicabinet-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: medicabinet-db
    restart: always
    environment:
      POSTGRES_USER: medicabinet
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: medicabinet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
